# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0002_room_is_scripted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='room',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='generics.Room'),
        ),
        migrations.AlterField(
            model_name='item',
            name='room',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='generics.Room'),
        ),
    ]
