# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0003_auto_20170318_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='js_filename',
            field=models.CharField(default='normalroom', max_length=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='code_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
