# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0004_auto_20170318_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
