# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0008_room_opening_script'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='room',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='character',
            name='name',
        ),
        migrations.AddField(
            model_name='character',
            name='first_name',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='last_name',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
