# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0009_auto_20170331_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='exit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generics.Room'),
        ),
    ]
