# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0010_auto_20170331_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.SET_DEFAULT, to='generics.Room'),
        ),
    ]
