# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0011_auto_20170331_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
