# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='room',
        ),
        migrations.RemoveField(
            model_name='item',
            name='room',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='puzzle_location',
        ),
        migrations.RemoveField(
            model_name='room',
            name='exit',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Puzzle',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
