# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0007_auto_20170330_0424'),
        ('players', '0002_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='location',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.SET_DEFAULT, to='generics.Room'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=16),
        ),
    ]
