# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0009_auto_20170331_1852'),
        ('players', '0004_auto_20170330_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerToCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generics.Character')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='location',
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playertocharacters',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
